export const SERVICE_URL = {
	home: '/',
	login: '/login',
	oauth2Register: '/oauth2/register',
	oauth2Callback: '/oauth2/callback',
	signUp: '/sign-up',
	certifications: '/certifications',
	announcements: '/announcements',
	announcementsDetail: '/announcementsDetail',
	mypage: '/mypage',
	community: '/community',
	manageGoal: '/manage-goal',
	pushNotice: '/mypage/push-notice',
	goalRegister: '/goals/register',
	inspection: '/admin/inspection',
	adminAnnouncements: '/admin/announcements',
	setting: '/setting',
};
